services:
  # 🌐 Web Service
  - type: web
    name: auth-system
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.22.2

      # Redis connection
      - key: REDIS_HOST
        fromService:
          type: redis
          name: auth-system-redis
          property: host

      - key: REDIS_PORT
        fromService:
          type: redis
          name: auth-system-redis
          property: port

      # Example (keep yours if already used)
      - key: NODE_ENV
        value: production


  # ⚙️ Campaign Mail Worker
  - type: worker
    name: campaign-mail-worker
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/workers/campaignMailWorker.js
    envVars:
      - key: NODE_VERSION
        value: 22.22.2

      - key: REDIS_HOST
        fromService:
          type: redis
          name: auth-system-redis
          property: host

      - key: REDIS_PORT
        fromService:
          type: redis
          name: auth-system-redis
          property: port

      - key: NODE_ENV
        value: production


  # ⚙️ Mail Template Worker
  - type: worker
    name: mail-template-worker
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node src/workers/mailTemplateWorker.js
    envVars:
      - key: NODE_VERSION
        value: 22.22.2

      - key: REDIS_HOST
        fromService:
          type: redis
          name: auth-system-redis
          property: host

      - key: REDIS_PORT
        fromService:
          type: redis
          name: auth-system-redis
          property: port

      - key: NODE_ENV
        value: production


  # 🧠 Redis (shared by all services)
    - type: redis
      name: auth-system-redis
      plan: free
      ipAllowList:
        - source: 0.0.0.0/0
          description: allow all (internal services)
